import {
  readArchitectureDepthScoringEnabled,
  readConfidencePauseThreshold,
  readContractNodePauseThreshold,
  readDebugFeedbackLoopRuntimeHard,
  readPauseContractNodesEnabled,
  readRedGreenGateMode,
  readSdkPathContractLintMode,
  readPythonExportContractLintMode,
  readPythonModuleContractLintMode,
  readTestQualityLintMode,
  readBehaviorSpecLintMode,
  readDemoArtifactLintMode,
  readPythonPypiSymbolLintMode,
  readStaticAnalysisEnabled,
  readTestRunFailurePlaybookEnabled,
  readTestRunPreflightEnabled,
  readTestRunAutoNpmInstallEnabled,
  readCharterAutoAnswerMode,
  readHitlDecisionMode,
} from '../settings/SettingsReaders';

export const qualityGateSettingsReaders = {
  readRedGreenGateMode,
  readDebugFeedbackLoopRuntimeHard,
  readTestRunPreflightEnabled,
  readTestRunAutoNpmInstallEnabled,
  readSdkPathContractLintMode,
  readPythonExportContractLintMode,
  readPythonModuleContractLintMode,
  readTestQualityLintMode,
  readBehaviorSpecLintMode,
  readDemoArtifactLintMode,
  readPythonPypiSymbolLintMode,
  readStaticAnalysisEnabled,
  readConfidencePauseThreshold,
  readContractNodePauseThreshold,
  readPauseContractNodesEnabled,
  readArchitectureDepthScoringEnabled,
  readTestRunFailurePlaybookEnabled,
  readCharterAutoAnswerMode,
  readHitlDecisionMode,
};
